json.id question.id
json.question_text question.question_text
json.question_type question.question_type
json.slug question.slug
json.answer_options question.answer_options
json.answer_min question.answer_min
json.answer_max question.answer_max
json.enabled question.enabled
json.updated_at question.updated_at
json.created_at question.created_at
